### ISSUE TITLE
ImportError: No module named djcelery (yet pip install says it is there)

### ISSUE THREAD

**Issue by brycenesbitt** [p2pu/lernanta#87]
What could be missing here?  djcelery can't be found, yet pip says it is already installed:

```
[bnesbitt@web309 myaskbot2]$ python settings.py
Traceback (most recent call last):
  File "settings.py", line 221, in <module>
    import djcelery
ImportError: No module named djcelery

[bnesbitt@web309 myaskbot2]$ python
>>> import djcelery
ImportError: No module named djcelery
>>> import django-celery
  File "<stdin>", line 1
    import django-celery
                 ^
SyntaxError: invalid syntax
>>> 

[bnesbitt@web309 myaskbot2]$ pip install django-celery
Requirement already satisfied (use --upgrade to upgrade): django-celery in /home/bnesbitt/lib/python2.7/django_celery-2.2.7-py2.7.egg
Requirement already satisfied (use --upgrade to upgrade): django-picklefield in /home/bnesbitt/lib/python2.7/django_picklefield-0.1.9-py2.7.egg (from django-celery)
Requirement already satisfied (use --upgrade to upgrade): celery==2.2.7 in /home/bnesbitt/lib/python2.7/celery-2.2.7-py2.7.egg (from django-celery)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil>=1.5.0,<2.0.0 in /home/bnesbitt/lib/python2.7/python_dateutil-1.5-py2.7.egg (from celery==2.2.7->django-celery)
Requirement already satisfied (use --upgrade to upgrade): anyjson>=0.3.1 in /home/bnesbitt/lib/python2.7/anyjson-0.3.1-py2.7.egg (from celery==2.2.7->django-celery)
Requirement already satisfied (use --upgrade to upgrade): kombu>=1.1.2,<2.0.0 in /home/bnesbitt/lib/python2.7/kombu-1.5.1-py2.7.egg (from celery==2.2.7->django-celery)
Requirement already satisfied (use --upgrade to upgrade): pyparsing>=1.5.0,<2.0.0 in /home/bnesbitt/lib/python2.7/pyparsing-1.5.6-py2.7.egg (from celery==2.2.7->django-celery)
Requirement already satisfied (use --upgrade to upgrade): amqplib>=1.0 in /home/bnesbitt/lib/python2.7/amqplib-1.0.2-py2.7.egg (from kombu>=1.1.2,<2.0.0->celery==2.2.7->django-celery)
Cleaning up...

[bnesbitt@web309 myaskbot2]$ yolk --list
DecoratorTools  - 1.7          - active 
MySQL-python    - 1.2.2        - active 
setuptools      - 0.6c9        - active 
yolk            - 0.4.1        - active development (/home/bnesbitt/lib/python2.4/yolk-0.4.1-py2.4.egg)
''''
```

**Comment by Naman-ntc** [comment]
as [http://docs.celeryproject.org/projects/django-celery/en/2.4/introduction.html](celery docs) clearly state you have to first migrate using `python manage.py migrate djcelery`
I was facing the same issue, this helped!
